name: Cancel Preview

on:
  pull_request:
    branches: [main]
    types: [synchronize, unlabeled, closed]

jobs:
  # If a new commit is added while the PR is in preview, or if the in-preview label is manually removed, or if the PR is closed without merging, the approval process and preview version will be canceled.
  cancel-preview:
    if: |
      (github.event.action == 'closed' && !github.event.pull_request.merged) ||
      (!github.event.pull_request.merged &&
        (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'in-preview')) ||
        (github.event.action == 'unlabeled' && !contains(github.event.pull_request.labels.*.name, 'in-preview'))) &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Remove in-preview label
        if: contains(github.event.pull_request.labels.*.name, 'in-preview')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "in-preview"
            })

      - name: Undeploy preview
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd ./krustberry.xyz
            docker compose -p ${{ github.event.pull_request.head.sha }} down preview

            # Removing image locally
            docker rmi ${{ vars.IMAGE_NAME }}:${{ github.event.pull_request.head.sha }}

      - name: Remove the image from Docker Registry
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_PASSWORD }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -X DELETE -H "Authorization: JWT $TOKEN" https://hub.docker.com/v2/repositories/${{ vars.IMAGE_NAME }}/tags/${{ github.event.pull_request.head.sha }}

      - name: Post comment about canceling preview
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "⛔️ Release rejected. The preview has been undeployed, and the `in-preview` label has been removed."
            })
