name: CD - Production Deployment

on: workflow_dispatch

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd ./krustberry.xyz
            export PREVIEW_IMAGE=${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.event.client_payload.sha }}
            docker compose down production
            docker compose up production -d

      - name: Update Slack notification about successful production deployment
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            ts: "${{ steps.slack.outputs.ts }}"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "Release deployed to production"

              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Commit ID:*\${{ github.sha }}"
                  - type: "mrkdwn"
                    text: "*Created by:*\n<${{ github.event.pusher.email }}|${{ github.event.pusher.name }}>"
                  - type: "mrkdwn"
                    text: "*When:*\n${{ github.event.head_commit.timestamp }}"
