name: CD - Release Rejection

on:
  workflow_dispatch:
    inputs:
      sha:
        type: "string"
        description: "Commit ID"
        required: true
      ts:
        type: "string"
        description: "Slack Message ID"
        required: true

jobs:
  revert-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Revert main to previous commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git revert --no-commit ${{ inputs.sha }}
          git commit -m "Revert main to previous commit due to rejection"
          git push origin main

      - name: Get latest commit hash
        id: get_hash
        run: echo "LATEST_HASH=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - name: Delete rejected Docker image and redeploy preview
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            # Delete the rejected Docker image
            docker rmi ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ inputs.sha }}

            # Reverting preview to the latest released version
            cd ./krustberry.xyz
            export PREVIEW_IMAGE=${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ steps.get_hash.outputs.LATEST_HASH }}
            docker compose down preview
            docker compose up traefik preview -d --no-recreate

      - name: Update Slack notification about rejection
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            ts: "${{ inputs.ts }}"
            text: "⛔️ Release has been rejected"
