name: CD - Release Rejection

on:
  workflow_dispatch:
    inputs:
      sha:
        type: "string"
        description: "Commit ID"
        required: true
      ts:
        type: "string"
        description: "Slack Message ID"
        required: true

jobs:
  revert-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Create revert PR
        run: |
         # Configure git
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          
          # Create a new branch for the revert
          SHORT_SHA=$(echo ${{ inputs.sha }} | cut -c1-7)
          BRANCH_NAME="revert-${SHORT_SHA}"
          git checkout -b $BRANCH_NAME
          
          # Create the revert commit
          git revert --no-edit ${{ inputs.sha }}
          
          # Push the branch
          git push origin $BRANCH_NAME
          
          # Create PR using GitHub CLI
          gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"
          PR_URL=$(gh pr create \
            --base main \
            --head $BRANCH_NAME \
            --title "Revert rejected release ${SHORT_SHA}" \
            --body "Automatically created revert PR for rejected release." \
            --label "automated-revert" \
            --json url --jq .url)
          
          # Get list of admin users
          ADMINS=$(gh api /repos/${{ github.repository }}/collaborators --jq '.[] | select(.permissions.admin == true) | .login')
          
          # Assign admins to the PR
          for admin in $ADMINS; do
            gh pr edit $PR_URL --add-assignee $admin
          done

      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - name: Redeploy preview
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            cd ./krustberry.xyz
            export PREVIEW_IMAGE=${{ vars.IMAGE_NAME }}:latest
            docker compose down preview
            docker compose up traefik preview -d --no-recreate

      - name: Remove rejected Docker image
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_PASSWORD }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -X DELETE -H "Authorization: JWT $TOKEN" https://hub.docker.com/v2/repositories/${{ vars.IMAGE_NAME }}/tags/${{ inputs.sha }}

      - name: Update Slack notification about rejection
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            ts: "${{ inputs.ts }}"
            text: "⛔️ Release has been rejected. A revert PR has been created."
