name: CD

on:
  push:
    branches: [main]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy preview version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            export PREVIEW_IMAGE=${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ needs.ci.outputs.sha }}
            docker compose down preview
            docker compose up preview -d
            
      - name: Send Slack notification for production approval
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "New release request"

              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Commit ID:*\${{ needs.ci.outputs.sha }}"
                  - type: "mrkdwn"
                    text: "*Created by:*\n<${{ github.event.pusher.email }}|${{ github.event.pusher.name }}>"
                  - type: "mrkdwn"
                    text: "*When:*\n${{ github.event.head_commit.timestamp }}"

              - type: "actions"
                elements:
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Approve"
                    style: "primary"
                    value: "${{ needs.ci.outputs.sha }}"
                    action_id: "approve_production_deploy"

                  - type: "button"
                    text: 
                      type: "plain_text"
                      text: "Reject"
                    style: "danger"
                    value: "${{ needs.ci.outputs.sha }}"
                    action_id: "reject_production_deploy"
