name: CD

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy preview version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd ./krustberry.xyz
            export PREVIEW_IMAGE=${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.event.pull_request.head.sha }}
            docker compose down preview
            docker compose up traefik preview -d --no-recreate
            
      - name: Send Slack notification for production approval
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "New release request"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "New release request"
              - type: "divider"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Commit ID:*\n${{ github.event.pull_request.head.sha }}"
                  - type: "mrkdwn"
                    text: "*Merged by:*\n<${{ github.event.pull_request.merged_by.name }} | @${{ github.event.pull_request.merged_by.login }}>"
                  - type: "mrkdwn"
                    text: "\n*When:*\n${{ github.event.pull_request.merged_at }}"
              - type: "actions"
                elements:
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Approve"
                    style: "primary"
                    value: "${{ github.event.pull_request.head.sha }}"
                    action_id: "approve_production_deploy"
                  - type: "button"
                    text:
                      type: "plain_text"
                      text: "Reject"
                    style: "danger"
                    value: "${{ github.event.pull_request.head.sha }}"
                    action_id: "reject_production_deploy"
              - type: "divider"
