name: CI-CD

on:
  pull_request:
    branches: [main]
    types: [labeled]
    
jobs:
  prepare:
    if: |
      !github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'in-preview') &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    outputs:
      clean_id: ${{ steps.clean_id.outputs.clean_id }}
    steps:
      - name: Get clean node_id
        id: clean_id
        run: |
          FULL_ID="${{ github.event.pull_request.node_id }}"
          CLEAN_ID=${FULL_ID#PR_}
          CLEAN_ID_LOWER=$(echo $CLEAN_ID | tr '[:upper:]' '[:lower:]')
          echo "clean_id=$CLEAN_ID_LOWER" >> $GITHUB_OUTPUT
  
  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests and validate code coverage
        run: pnpm run test:coverage

  build:
    needs: [prepare, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # Cache the build output
      - name: Cache build artifacts
        uses: actions/cache/save@v4
        with:
          path: .next
          key: ${{ runner.os }}-build-${{ github.event.pull_request.head.sha }}

  create-docker-image:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Restore cached build artifacts
      - name: Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: .next
          key: ${{ runner.os }}-build-${{ github.event.pull_request.head.sha }}
          fail-on-cache-miss: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.IMAGE_NAME }}:${{ needs.prepare.outputs.clean_id }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy-preview:
    needs: [prepare, create-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy preview version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd ./krustberry.xyz
            export PREVIEW_IMAGE=${{ needs.prepare.outputs.clean_id }}
            docker compose -p latest up traefik -d --no-recreate
            docker compose -p ${{ needs.prepare.outputs.clean_id }} up preview -d

  send-notifications:
    needs: [prepare, deploy-preview]
    runs-on: ubuntu-latest
    steps:
      - name: Post a comment with the preview link
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "✅ Preview version has been deployed: [${{ needs.prepare.outputs.clean_id }}.krustberry.xyz](https://${{ needs.prepare.outputs.clean_id }}.krustberry.xyz)"
            })
