name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited]

jobs:
  test-and-build:
    # We skip CI and CD if PR is labelled "automated-revert"
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'automated-revert') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests and validate code coverage
        run: pnpm run test:coverage

      - name: Build
        run: pnpm run build

      # Cache the build output and node_modules
      - name: Cache build artifacts
        uses: actions/cache/save@v4
        with:
          path: .next
          key: ${{ runner.os }}-build-${{ github.sha }}

  docker:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Restore cached build artifacts
      - name: Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: .next
          key: ${{ runner.os }}-build-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.IMAGE_NAME }}:${{ github.event.pull_request.head.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
