name: Closed Pull Request

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  remove-docker-image:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Remove Docker Image from registry
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_PASSWORD }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -X DELETE -H "Authorization: JWT $TOKEN" https://hub.docker.com/v2/repositories/${{ vars.IMAGE_NAME }}/tags/${{ github.event.pull_request.head.sha }}
